[default]
extend-ignore-re = [
    "iMatix"
]

[default.extend-words]
annote = "annote"
inbrace = "inbrace"
BA = "BA"
FO = "FO"
ND = "ND"

[default.extend-identifiers]
"CC-BY-NC-ND-1.0" = "CC-BY-NC-ND-1.0"
"CC-BY-NC-ND-2.0" = "CC-BY-NC-ND-2.0"
"CC-BY-NC-ND-2.5" = "CC-BY-NC-ND-2.5"
"CC-BY-NC-ND-3.0" = "CC-BY-NC-ND-3.0"
"CC-BY-NC-ND-3.0-IGO" = "CC-BY-NC-ND-3.0-IGO"
"CC-BY-NC-ND-4.0" = "CC-BY-NC-ND-4.0"
"CC-BY-ND-1.0" = "CC-BY-ND-1.0"
"CC-BY-ND-2.0" = "CC-BY-ND-2.0"
"CC-BY-ND-2.5" = "CC-BY-ND-2.5"
"CC-BY-ND-3.0" = "CC-BY-ND-3.0"
"CC-BY-ND-4.0" = "CC-BY-ND-4.0"